
CREATE DATABASE CompuStore_Grupo03
go

Use CompuStore_Grupo03

go


CREATE TABLE GRMGRU
( 
	GRMGRU_CODGRU        varchar(20)  NOT NULL ,
	GRMGRU_DESCRP        varchar(100)  NOT NULL ,
	GRMGRU_SITUAC        char(1)  NOT NULL ,
	GRMGRU_USUALT        varchar(20)  NOT NULL ,
	GRMGRU_USUMOD        varchar(20)  NOT NULL ,
	GRMGRU_FECALT        datetime  NOT NULL ,
	GRMGRU_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE GRMGRU
	ADD CONSTRAINT XPKGrupo_Usuario PRIMARY KEY  CLUSTERED (GRMGRU_CODGRU ASC)
go



CREATE TABLE GRMUSUA
( 
	GRMUSU_CODUSU        varchar(20)  NOT NULL ,
	GRMUSU_DESCRP        varchar(100)  NOT NULL ,
	GRMUSU_CLAVES        varchar(50)  NOT NULL ,
	GRMUSU_CORREO        varchar(50)  NULL ,
	GRMUSU_SITUAC        char(1)  NOT NULL ,
	GRMUSU_ESTADM        char(1)  NOT NULL ,
	GRMUSU_USUALT        varchar(20)  NOT NULL ,
	GRMUSU_USUMOD        varchar(20)  NOT NULL ,
	GRMUSU_FECALT        datetime  NOT NULL ,
	GRMUSU_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE GRMUSUA
	ADD CONSTRAINT XPKUsuario PRIMARY KEY  CLUSTERED (GRMUSU_CODUSU ASC)
go



CREATE TABLE GRRGUS
( 
	GRRGUS_CODGRU        varchar(20)  NOT NULL ,
	GRRGUS_CODUSU        varchar(20)  NOT NULL ,
	GRRGUS_USUALT        varchar(20)  NOT NULL ,
	GRRGUS_USUMOD        varchar(20)  NOT NULL ,
	GRRGUS_FECALT        datetime  NOT NULL ,
	GRRGUS_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE GRRGUS
	ADD CONSTRAINT XPKRelacion_Grupo_Usuario PRIMARY KEY  CLUSTERED (GRRGUS_CODGRU ASC,GRRGUS_CODUSU ASC)
go



CREATE TABLE GRTAGR
( 
	GRTAGR_CODGRU        varchar(20)  NOT NULL ,
	GRTAGR_PERALT        char(1)  NOT NULL ,
	GRTAGR_PERMOD        char(1)  NOT NULL ,
	GRTAGR_PERELI        char(1)  NOT NULL ,
	GRTAGR_PERCON        char(1)  NOT NULL ,
	GRTAGR_USUALT        varchar(20)  NOT NULL ,
	GRTAGR_USUMOD        varchar(20)  NOT NULL ,
	GRTAGR_FECALT        datetime  NOT NULL ,
	GRTAGR_FECMOD        datetime  NOT NULL ,
	GRTAGR_OBJETO        varchar(20)  NOT NULL 
)
go



ALTER TABLE GRTAGR
	ADD CONSTRAINT XPKAcceso_Grupo PRIMARY KEY  CLUSTERED (GRTAGR_CODGRU ASC,GRTAGR_OBJETO ASC)
go



CREATE TABLE GRTAUS
( 
	GRTAUS_CODUSU        varchar(20)  NOT NULL ,
	GRTAUS_OBJETO        varchar(20)  NOT NULL ,
	GRTAUS_PERALT        char(1)  NOT NULL ,
	GRTAUS_PERMOD        char(1)  NOT NULL ,
	GRTAUS_PERELI        char(1)  NOT NULL ,
	GRTAUS_PERCON        char(1)  NOT NULL ,
	GRTAUS_USUALT        varchar(20)  NOT NULL ,
	GRTAUS_USUMOD        varchar(20)  NOT NULL ,
	GRTAUS_FECALT        datetime  NOT NULL ,
	GRTAUS_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE GRTAUS
	ADD CONSTRAINT XPKAcceso_Usuario PRIMARY KEY  CLUSTERED (GRTAUS_CODUSU ASC,GRTAUS_OBJETO ASC)
go



CREATE TABLE GRTCPA
( 
	GRTCPA_CONPAG        varchar(6)  NOT NULL ,
	GRTCPA_TIPPAG        char(3)  NOT NULL ,
	GRTCPA_DIACRE        integer  NULL ,
	GRTCPA_SITUAC        char(1)  NOT NULL ,
	GRTCPA_USUALT        varchar(20)  NOT NULL ,
	GRTCPA_USUMOD        varchar(20)  NOT NULL ,
	GRTCPA_FECALT        datetime  NOT NULL ,
	GRTCPA_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE GRTCPA
	ADD CONSTRAINT XPKCondicion_Pago PRIMARY KEY  CLUSTERED (GRTCPA_CONPAG ASC)
go



CREATE TABLE GRTMON
( 
	GRTMON_MONEDA        varchar(3)  NOT NULL ,
	GRTMON_DESCRP        varchar(50)  NOT NULL ,
	GRTMON_SITUAC        char(1)  NOT NULL ,
	GRTMON_USUALT        varchar(20)  NOT NULL ,
	GRTMON_USUMOD        varchar(20)  NOT NULL ,
	GRTMON_FECALT        datetime  NOT NULL ,
	GRTMON_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE GRTMON
	ADD CONSTRAINT XPKMoneda PRIMARY KEY  CLUSTERED (GRTMON_MONEDA ASC)
go



CREATE TABLE GRTUME
( 
	GRTUME_UNIMED        varchar(3)  NOT NULL ,
	GRTUME_DESCRP        varchar(50)  NOT NULL ,
	GRTUME_SITUAC        char(1)  NOT NULL ,
	GRTUME_USUALT        varchar(20)  NOT NULL ,
	GRTUME_USUMOD        varchar(20)  NOT NULL ,
	GRTUME_FECALT        datetime  NOT NULL ,
	GRTUME_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE GRTUME
	ADD CONSTRAINT XPKUnidad_Medida PRIMARY KEY  CLUSTERED (GRTUME_UNIMED ASC)
go



CREATE TABLE STMPRO
( 
	STMPRO_TIPPRO        char(6)  NOT NULL ,
	STMPRO_ARTCOD        varchar(20)  NOT NULL ,
	STMPRO_DESPRO        varchar(100)  NULL ,
	STMPRO_UNIMED        varchar(3)  NULL ,
	STMPRO_PRECIO        numeric(16,4)  NULL ,
	STMPRO_NACIMP        varchar(3)  NOT NULL ,
	STMPRO_SITUAC        char(1)  NOT NULL ,
	STMPRO_USUALT        varchar(20)  NOT NULL ,
	STMPRO_USUMOD        varchar(20)  NOT NULL ,
	STMPRO_FECALT        datetime  NOT NULL ,
	STMPRO_FECMOD        datetime  NOT NULL ,
	STMPRO_IMAGEN        varbinary(max)  NULL ,
	STMPRO_CNTMIN        numeric(16,4)  NOT NULL ,
	STMPRO_CNTMAX        numeric(16,4)  NOT NULL ,
	STMPRO_CODPRO        varchar(20)  NULL ,
	STMPRO_MARCAS        varchar(20)  NULL ,
	STMPRO_MODELO        varchar(20)  NULL ,
	STMPRO_PREVTA        numeric(16,4)  NULL ,
	STMPRO_MONEDA        varchar(3)  NULL 
)
go



ALTER TABLE STMPRO
	ADD CONSTRAINT XPKProducto PRIMARY KEY  CLUSTERED (STMPRO_TIPPRO ASC,STMPRO_ARTCOD ASC)
go



CREATE TABLE STPSTO
( 
	STPSTO_TIPPRO        char(6)  NOT NULL ,
	STPSTO_ARTCOD        varchar(20)  NOT NULL ,
	STPSTO_STOACT        int  NOT NULL ,
	STPSTO_USUALT        varchar(20)  NOT NULL ,
	STPSTO_USUMOD        varchar(20)  NOT NULL ,
	STPSTO_FECALT        datetime  NOT NULL ,
	STPSTO_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE STPSTO
	ADD CONSTRAINT XPKStock_Producto PRIMARY KEY  CLUSTERED (STPSTO_TIPPRO ASC,STPSTO_ARTCOD ASC)
go



CREATE TABLE STTPRO
( 
	STTPRO_TIPPRO        char(6)  NOT NULL ,
	STTPRO_DESCRP        varchar(50)  NOT NULL ,
	STTPRO_PROSTO        char(1)  NOT NULL ,
	STTPRO_SITUAC        char(1)  NOT NULL ,
	STTPRO_USUALT        varchar(20)  NOT NULL ,
	STTPRO_USUMOD        varchar(20)  NOT NULL ,
	STTPRO_FECALT        datetime  NOT NULL ,
	STTPRO_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE STTPRO
	ADD CONSTRAINT XPKTipo_Producto PRIMARY KEY  CLUSTERED (STTPRO_TIPPRO ASC)
go



CREATE TABLE VTMCLI
( 
	VTMCLI_CODCLI        varchar(20)  NOT NULL ,
	VTMCLI_NOMCLI        varchar(100)  NOT NULL ,
	VTMCLI_NRORUC        varchar(20)  NULL ,
	VTMCLI_DIRECC        varchar(100)  NOT NULL ,
	VTMCLI_TIPCLI        char(1)  NOT NULL ,
	VTMCLI_TELEFO        varchar(20)  NULL ,
	VTMCLI_CORREO        varchar(50)  NULL ,
	VTMCLI_USUALT        varchar(20)  NOT NULL ,
	VTMCLI_USUMOD        varchar(20)  NOT NULL ,
	VTMCLI_FECALT        datetime  NOT NULL ,
	VTMCLI_FECMOD        datetime  NOT NULL ,
	VTMCLI_CODPAI        varchar(3)  NULL ,
	VTMCLI_SITUAC        char(1)  NOT NULL ,
	VTMCLI_CODPAG        varchar(3)  NULL ,
	VTMCLI_CONPAG        varchar(6)  NULL 
)
go



ALTER TABLE VTMCLI
	ADD CONSTRAINT XPKCliente PRIMARY KEY  CLUSTERED (VTMCLI_CODCLI ASC)
go



CREATE TABLE VTRMVC
( 
	VTRMVC_CODAPL        char(6)  NOT NULL ,
	VTRMVC_NROAPL        int  NOT NULL ,
	VTRMVC_FCHVNC        date  NOT NULL ,
	VTRMVC_CODCLI        varchar(20)  NOT NULL ,
	VTRMVC_IMPNAC        numeric(16,4)  NOT NULL ,
	VTRMVC_IMPSEC        numeric(16,4)  NOT NULL ,
	VTRMVC_TIPCAM        numeric(16,4)  NOT NULL ,
	VTRMVC_FCHEMI        date  NOT NULL ,
	VTRMVC_CONPAG        varchar(3)  NOT NULL ,
	VTRMVC_MONEDA        varchar(3)  NOT NULL ,
	VTRMVC_USUALT        datetime  NOT NULL ,
	VTRMVC_USUMOD        varchar(20)  NOT NULL ,
	VTRMVC_FECALT        datetime  NOT NULL ,
	VTRMVC_FECMOD        datetime  NOT NULL ,
	VTRMVC_CODFOR        char(6)  NOT NULL ,
	VTRMVC_NROFOR        int  NOT NULL 
)
go



ALTER TABLE VTRMVC
	ADD CONSTRAINT XPKDocumento_Cliente_CtaCte PRIMARY KEY  CLUSTERED (VTRMVC_CODFOR ASC,VTRMVC_NROFOR ASC,VTRMVC_CODAPL ASC,VTRMVC_NROAPL ASC)
go



CREATE TABLE VTRMVH
( 
	VTRMVH_CODFOR        varchar(6)  NOT NULL ,
	VTRMVH_NROFOR        int  NOT NULL ,
	VTRMVH_MONEDA        varchar(3)  NULL ,
	VTRMVH_FCHEMI        date  NOT NULL ,
	VTRMVH_SERIED        varchar(4)  NOT NULL ,
	VTRMVH_GLOSAS        varchar(100)  NOT NULL ,
	VTRMVH_TIPCAM        numeric(16,4)  NOT NULL ,
	VTRMVH_USUALT        varchar(20)  NOT NULL ,
	VTRMVH_USUMOD        varchar(20)  NOT NULL ,
	VTRMVH_FECALT        datetime  NOT NULL ,
	VTRMVH_FECMOD        datetime  NOT NULL ,
	VTRMVH_CODCLI        varchar(20)  NOT NULL ,
	VTRMVH_NRODOC        varchar(20)  NOT NULL ,
	VTRMVH_CODANU        varchar(6)  NULL ,
	VTRMVH_NROANU        int  NULL ,
	VTRMVH_CONPAG        varchar(6)  NULL 
)
go



ALTER TABLE VTRMVH
	ADD CONSTRAINT XPKDocumento_Cliente_Cabecera PRIMARY KEY  CLUSTERED (VTRMVH_CODFOR ASC,VTRMVH_NROFOR ASC)
go



CREATE TABLE VTRMVI
( 
	VTRMVI_CODFOR        varchar(6)  NOT NULL ,
	VTRMVI_NROFOR        int  NOT NULL ,
	VTRMVI_NROITM        int  NOT NULL ,
	VTRMVI_IMPDEB        numeric(16,4)  NOT NULL ,
	VTRMVI_SECHAB        numeric(16,4)  NOT NULL ,
	VTRMVI_TIPPRO        char(6)  NOT NULL ,
	VTRMVI_ARTCOD        varchar(20)  NOT NULL ,
	VTRMVI_USUALT        varchar(20)  NOT NULL ,
	VTRMVI_USUMOD        varchar(20)  NOT NULL ,
	VTRMVI_FECALT        datetime  NOT NULL ,
	VTRMVI_FECMOD        datetime  NOT NULL ,
	VTRMVI_PRECIO        numeric(16,4)  NOT NULL ,
	VTRMVI_CANTID        int  NOT NULL 
)
go



ALTER TABLE VTRMVI
	ADD CONSTRAINT XPKDocumento_Cliente_Detalle PRIMARY KEY  CLUSTERED (VTRMVI_CODFOR ASC,VTRMVI_NROFOR ASC,VTRMVI_NROITM ASC)
go



CREATE TABLE VTTPCL
( 
	VTTPCL_CODCLI        varchar(20)  NOT NULL ,
	VTTPCL_FCHINI        datetime  NOT NULL ,
	VTTPCL_FCHFIN        datetime  NOT NULL ,
	VTTPCL_APLIMP        char(1)  NOT NULL ,
	VTTPCL_IMPORT        numeric(16,4)  NULL ,
	VTTPCL_PORDES        numeric(16,4)  NULL ,
	VTTPCL_SITUAC        char(1)  NOT NULL ,
	VTTPCL_USUALT        varchar(20)  NOT NULL ,
	VTTPCL_USUMOD        varchar(20)  NOT NULL ,
	VTTPCL_FECALT        datetime  NOT NULL ,
	VTTPCL_FECMOD        datetime  NOT NULL 
)
go



ALTER TABLE VTTPCL
	ADD CONSTRAINT XPKPromocion_Cliente PRIMARY KEY  CLUSTERED (VTTPCL_CODCLI ASC,VTTPCL_FCHINI ASC,VTTPCL_FCHFIN ASC)
go



CREATE TABLE VTTPPR
( 
	VTTPPR_TIPPRO        char(6)  NOT NULL ,
	VTTPPR_FCHINI        datetime  NOT NULL ,
	VTTPPR_FCHFIN        datetime  NOT NULL ,
	VTTPPR_CNTMIN        numeric(16,4)  NULL ,
	VTTPPR_PORDES        numeric(16,4)  NULL ,
	VTTPPR_SITUAC        char(1)  NOT NULL ,
	VTTPPR_USUALT        varchar(20)  NOT NULL ,
	VTTPPR_USUMOD        varchar(20)  NOT NULL ,
	VTTPPR_FECALT        datetime  NOT NULL ,
	VTTPPR_FECMOD        datetime  NOT NULL ,
	VTTPPR_ARTCOD        varchar(20)  NOT NULL ,
	VTTPPR_APLCNT        char(1)  NOT NULL 
)
go



ALTER TABLE VTTPPR
	ADD CONSTRAINT XPKPromocion_Producto PRIMARY KEY  CLUSTERED (VTTPPR_TIPPRO ASC,VTTPPR_ARTCOD ASC,VTTPPR_FCHINI ASC,VTTPPR_FCHFIN ASC)
go



CREATE TABLE VTTPTP
( 
	VTTPTP_TIPPRO        char(6)  NOT NULL ,
	VTTPTP_FCHINI        datetime  NOT NULL ,
	VTTPTP_FCHFIN        datetime  NOT NULL ,
	VTTPTP_CNTMIN        numeric(16,4)  NULL ,
	VTTPTP_PORDES        numeric(16,4)  NULL ,
	VTTPTP_SITUAC        char(1)  NOT NULL ,
	VTTPTP_USUALT        varchar(20)  NOT NULL ,
	VTTPTP_USUMOD        varchar(20)  NOT NULL ,
	VTTPTP_FECALT        datetime  NOT NULL ,
	VTTPTP_FECMOD        datetime  NOT NULL ,
	VTTPTP_APLCNT        char(1)  NOT NULL 
)
go



ALTER TABLE VTTPTP
	ADD CONSTRAINT XPKPromocion_Tipo_Producto PRIMARY KEY  CLUSTERED (VTTPTP_TIPPRO ASC,VTTPTP_FCHINI ASC,VTTPTP_FCHFIN ASC)
go




ALTER TABLE GRRGUS
	ADD CONSTRAINT R_10 FOREIGN KEY (GRRGUS_CODUSU) REFERENCES GRMUSUA(GRMUSU_CODUSU)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE GRRGUS
	ADD CONSTRAINT R_11 FOREIGN KEY (GRRGUS_CODGRU) REFERENCES GRMGRU(GRMGRU_CODGRU)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE GRTAGR
	ADD CONSTRAINT R_12 FOREIGN KEY (GRTAGR_CODGRU) REFERENCES GRMGRU(GRMGRU_CODGRU)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE GRTAUS
	ADD CONSTRAINT R_13 FOREIGN KEY (GRTAUS_CODUSU) REFERENCES GRMUSUA(GRMUSU_CODUSU)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE STMPRO
	ADD CONSTRAINT R_1 FOREIGN KEY (STMPRO_TIPPRO) REFERENCES STTPRO(STTPRO_TIPPRO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE STMPRO
	ADD CONSTRAINT R_28 FOREIGN KEY (STMPRO_UNIMED) REFERENCES GRTUME(GRTUME_UNIMED)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE STMPRO
	ADD CONSTRAINT R_29 FOREIGN KEY (STMPRO_MONEDA) REFERENCES GRTMON(GRTMON_MONEDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE STPSTO
	ADD CONSTRAINT R_3 FOREIGN KEY (STPSTO_TIPPRO,STPSTO_ARTCOD) REFERENCES STMPRO(STMPRO_TIPPRO,STMPRO_ARTCOD)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTMCLI
	ADD CONSTRAINT R_33 FOREIGN KEY (VTMCLI_CONPAG) REFERENCES GRTCPA(GRTCPA_CONPAG)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTRMVC
	ADD CONSTRAINT R_5 FOREIGN KEY (VTRMVC_CODCLI) REFERENCES VTMCLI(VTMCLI_CODCLI)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTRMVC
	ADD CONSTRAINT R_22 FOREIGN KEY (VTRMVC_MONEDA) REFERENCES GRTMON(GRTMON_MONEDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTRMVH
	ADD CONSTRAINT R_4 FOREIGN KEY (VTRMVH_CODCLI) REFERENCES VTMCLI(VTMCLI_CODCLI)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTRMVH
	ADD CONSTRAINT R_23 FOREIGN KEY (VTRMVH_MONEDA) REFERENCES GRTMON(GRTMON_MONEDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTRMVH
	ADD CONSTRAINT R_34 FOREIGN KEY (VTRMVH_CONPAG) REFERENCES GRTCPA(GRTCPA_CONPAG)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTRMVI
	ADD CONSTRAINT R_6 FOREIGN KEY (VTRMVI_TIPPRO,VTRMVI_ARTCOD) REFERENCES STMPRO(STMPRO_TIPPRO,STMPRO_ARTCOD)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTRMVI
	ADD CONSTRAINT R_8 FOREIGN KEY (VTRMVI_CODFOR,VTRMVI_NROFOR) REFERENCES VTRMVH(VTRMVH_CODFOR,VTRMVH_NROFOR)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTTPCL
	ADD CONSTRAINT R_30 FOREIGN KEY (VTTPCL_CODCLI) REFERENCES VTMCLI(VTMCLI_CODCLI)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTTPPR
	ADD CONSTRAINT R_32 FOREIGN KEY (VTTPPR_TIPPRO,VTTPPR_ARTCOD) REFERENCES STMPRO(STMPRO_TIPPRO,STMPRO_ARTCOD)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE VTTPTP
	ADD CONSTRAINT R_31 FOREIGN KEY (VTTPTP_TIPPRO) REFERENCES STTPRO(STTPRO_TIPPRO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


