package pe.jpaj.wilsonapp.view;

import javax.swing.JInternalFrame;
import pe.jpaj.wilsonapp.domain.UsuarioDomain;
import pe.jpaj.wilsonapp.util.Memoria;

/**
 *
 * @author Gustavo Coronel
 * @email gcoronelc@gmail.com
 * @blog www.desarrollasoftware.com
 */
public class FormularioMDI extends javax.swing.JFrame {

 
  public FormularioMDI() {
    initComponents();
    establecerTitulo();
    setExtendedState(MAXIMIZED_BOTH);
  }
  
  private void establecerTitulo(){
    UsuarioDomain bean;
    bean = (UsuarioDomain) Memoria.get("usuario");
    String titulo = " WilsonStore    [Usuario:" +
            bean.getUsuario()+ "]";
    setTitle(titulo);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArchivoParametros = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuArchivoSalir = new javax.swing.JMenuItem();
        menuProceso = new javax.swing.JMenu();
        menuProcesoMatricula = new javax.swing.JMenuItem();
        menuProcesoEliminaMatricula = new javax.swing.JMenuItem();
        menuProcesoCambiaMatricula = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuProcesoCrearCiclo = new javax.swing.JMenuItem();
        menuProcesoProgramarCurso = new javax.swing.JMenuItem();
        menuProcesoAsignarProfesor = new javax.swing.JMenuItem();
        menuTabla = new javax.swing.JMenu();
        menuConsulta = new javax.swing.JMenu();
        menuReporte = new javax.swing.JMenu();
        menuUtil = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDUTEC");

        menuArchivo.setText("Archivo");

        menuArchivoParametros.setText("Parámetros");
        menuArchivo.add(menuArchivoParametros);
        menuArchivo.add(jSeparator1);

        menuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuArchivoSalir.setText("Salir");
        menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoSalir);

        menuBar.add(menuArchivo);

        menuProceso.setText("Proceso");

        menuProcesoMatricula.setText("Matricula");
        menuProcesoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesoMatriculaActionPerformed(evt);
            }
        });
        menuProceso.add(menuProcesoMatricula);

        menuProcesoEliminaMatricula.setText("Eliminar Matricula");
        menuProcesoEliminaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesoEliminaMatriculaActionPerformed(evt);
            }
        });
        menuProceso.add(menuProcesoEliminaMatricula);

        menuProcesoCambiaMatricula.setText("Cambiar Matricula");
        menuProcesoCambiaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesoCambiaMatriculaActionPerformed(evt);
            }
        });
        menuProceso.add(menuProcesoCambiaMatricula);
        menuProceso.add(jSeparator2);

        menuProcesoCrearCiclo.setText("Crear Ciclo");
        menuProceso.add(menuProcesoCrearCiclo);

        menuProcesoProgramarCurso.setText("Programar Curso");
        menuProceso.add(menuProcesoProgramarCurso);

        menuProcesoAsignarProfesor.setText("Asignar Profesor");
        menuProceso.add(menuProcesoAsignarProfesor);

        menuBar.add(menuProceso);

        menuTabla.setText("Tabla");
        menuBar.add(menuTabla);

        menuConsulta.setText("Consulta");
        menuBar.add(menuConsulta);

        menuReporte.setText("Reporte");
        menuBar.add(menuReporte);

        menuUtil.setText("Util");
        menuBar.add(menuUtil);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_menuArchivoSalirActionPerformed

  private void menuProcesoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoMatriculaActionPerformed
    //cargaFormulario(ProcMatriculaView.class);
  }//GEN-LAST:event_menuProcesoMatriculaActionPerformed

  private void menuProcesoEliminaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoEliminaMatriculaActionPerformed
    //cargaFormulario(ProcRetiroView.class);
  }//GEN-LAST:event_menuProcesoEliminaMatriculaActionPerformed

  private void menuProcesoCambiaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoCambiaMatriculaActionPerformed
   // cargaFormulario(ProcTransferenciaView.class);
  }//GEN-LAST:event_menuProcesoCambiaMatriculaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormularioMDI().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuArchivoParametros;
    private javax.swing.JMenuItem menuArchivoSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuProceso;
    private javax.swing.JMenuItem menuProcesoAsignarProfesor;
    private javax.swing.JMenuItem menuProcesoCambiaMatricula;
    private javax.swing.JMenuItem menuProcesoCrearCiclo;
    private javax.swing.JMenuItem menuProcesoEliminaMatricula;
    private javax.swing.JMenuItem menuProcesoMatricula;
    private javax.swing.JMenuItem menuProcesoProgramarCurso;
    private javax.swing.JMenu menuReporte;
    private javax.swing.JMenu menuTabla;
    private javax.swing.JMenu menuUtil;
    // End of variables declaration//GEN-END:variables

  private void cargaFormulario(Class<?> aClass) {
    try {
      // Variable de control
      JInternalFrame view = null;
      // Buscar instancia
      for(JInternalFrame f: desktopPane.getAllFrames()){
        if(aClass.isInstance(f)){
          view = f;
          break;
        }
      }
      // Crear instancia
      if( view == null){
        view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
        view.setVisible(true);
      }
      // Activando el formulario
      view.setSelected(true);
      view.setMaximum(true);
    } catch (Exception e) {
    }
  }

}
